baseURL = 'https://unresolved-contradictions.co.uk'
languageCode = 'en-gb'
title = 'Unresolved Contradictions'
theme = 'PaperMod'
enableRobotsTXT = true

[params]
AuthorName = 'Unresolved Contradictions'
description = 'My thoughts on the world.'
keywords = ['Blog, politics, economics']
defaultTheme = 'auto'
defaultThemeToggle = true
ShowReadingTime = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false
    
  [params.homeInfoParams]
  Title = "Welcome to my thoughts..."
  Content = "This blog will mostly have my ideas and thoughts about the social world, politics, economics and philosophy."

  [params.assets]
  disableHLJS = true # to disable highlight.js
  disableFingerprinting = true

[minify]
disableXML = true
minifyOutput = true

