baseURL = 'https://unresolved-contradictions.co.uk'
languageCode = 'en-gb'
title = 'Unresolved Contradictions'
theme = 'PaperMod'

[params]
 [params.homeInfoParams]
  Title = "Hi there wave"
  Content = "Can be Info, links, about.."
