baseURL = 'https://unresolved-contradictions.co.uk'
languageCode = 'en-gb'
title = 'Unresolved Contradictions'
theme = 'PaperMod'

[params]
 [params.homeInfoParams]
  Title = "Welcome to my thoughts..."
  Content = "This blog will mostly have my ideas and thoughts about the social world, politics, economics and philosophy."
