baseURL = 'https://unresolved-contradictions.co.uk'
languageCode = 'en-gb'
title = 'Unresolved Contradictions'
theme = 'PaperModified'

enableRobotsTXT = true

paginate = 10

[permalinks]
post = "/:year/:title/"

[params]
title = 'Unresolved Contradictions'
AuthorName = 'Unresolved Contradictions'
description = 'My thoughts on the world.'
keywords = ['Blog, politics, economics']
defaultTheme = 'auto'
disableThemeToggle = false
ShowReadingTime = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false
    
  [params.homeInfoParams]
  Title = "Welcome to my thoughts..."
  Content = "This blog will mostly have my ideas and thoughts about the social world, politics, economics and philosophy."

  [params.assets]
  disableHLJS = true # to disable highlight.js
  disableFingerprinting = true

[menu]
[[menu.main]]
name = 'Search'
pageRef = '/search'
weight = 10

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[minify]
disableXML = true
minifyOutput = true

